### ISSUE TITLE
Fix eslint warnings and errors

### ISSUE THREAD

**Issue by NikolayYakovenko** [NikolayYakovenko/Player#11]
When eslint and its plugins were updated to the latest version, a lot of eslint warnings and errors appeared.
All warnings and errors should be fixed. If there are some troubles while fixing, try to change the rule in .eslintrc config.

**Comment by rsmelo** [comment]
May i work on this issue?

**Comment by NikolayYakovenko** [comment]
@rsmelo, sorry.
I have already started.

**Comment by NikolayYakovenko** [comment]
The issue was resolved in [this PR](https://github.com/NikolayYakovenko/Player/pull/12)
